//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VernTestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        public int id { get; set; }
        public Nullable<int> Health { get; set; }
        public Nullable<int> Lvl { get; set; }
        public Nullable<int> AttackPower { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Alive { get; set; }
    }
}
